### ISSUE TITLE
Giscus 댓글 시스템 설정 오류

### ISSUE THREAD

**Issue by SUNGMYEONGGI** [SUNGMYEONGGI/SUNGMYEONGGI.github.io#1]
## 문제점
현재 `_config.yml`의 giscus 설정에서 다음과 같은 문제가 발견되었습니다:

1. repo가 잘못 설정되어 있습니다: `repo: bluemiv/github-blog-comment`
   - 현재 다른 사용자의 레포지토리로 설정되어 있어 댓글 시스템이 제대로 작동하지 않을 수 있습니다.

## 해결 완료 ✅
Giscus 설정을 다음과 같이 업데이트했습니다:

```yaml
giscus:
  repo: SUNGMYEONGGI/SUNGMYEONGGI.github.io
  repo_id: 738532815
  category: Comments
  category_id: DIC_kwDONOmc3s4CYJ7c
  mapping: pathname
  strict: 0
  input_position: bottom
  lang: ko
  reactions_enabled: 1
```

## 추가 필요 사항
1. GitHub에 Giscus 앱이 설치되어 있는지 확인하세요
2. 저장소에 Discussions이 활성화되어 있는지 확인하세요
3. Comments 카테고리가 있는지 확인하고 없으면 생성하세요

이제 댓글 시스템이 정상적으로 작동할 것입니다.
