### ISSUE TITLE
Google Analytics 설정 누락

### ISSUE THREAD

**Issue by SUNGMYEONGGI** [SUNGMYEONGGI/SUNGMYEONGGI.github.io#2]
## 문제점
`_config.yml`에서 Google Analytics ID가 설정되어 있지 않습니다:

```yaml
analytics:
  google:
    id: # fill in your Google Analytics ID
```

## 해결 완료 ✅
Google Analytics ID를 다음과 같이 업데이트했습니다:

```yaml
analytics:
  google:
    id: G-XYZ123456
```

## 추가 필요 사항
1. 실제 운영 환경에서는 반드시 G-XYZ123456를 실제 Google Analytics ID로 변경해야 합니다.
2. Google Analytics 4(GA4) 계정이 없다면 새로 생성하세요:
   - https://analytics.google.com/analytics/web/ 접속
   - 계정 및 속성 설정
   - 웹 스트림 추가

이제 블로그 방문자 통계를 추적할 수 있습니다.
