### ISSUE TITLE
SEO 최적화를 위한 설정 개선 필요

### ISSUE THREAD

**Issue by SUNGMYEONGGI** [SUNGMYEONGGI/SUNGMYEONGGI.github.io#3]
## 문제점
현재 `_config.yml`의 SEO 관련 설정에서 개선이 필요한 부분들이 있습니다:

1. `social_preview_image`가 설정되어 있지 않습니다
2. 일부 소셜 미디어 링크가 비활성화되어 있습니다

## 해결 완료 ✅
SEO 관련 설정을 다음과 같이 개선했습니다:

1. 소셜 미디어 프리뷰 이미지 추가:
```yaml
social_preview_image: /assets/img/ogimage.jpg
```

2. 소셜 미디어 링크 활성화:
```yaml
social:
  links:
    - https://x.com/dev_ruatnec
    - https://github.com/SUNGMYEONGGI
    - https://www.linkedin.com/in/sungmyeonggi
```

3. 메타 설명 개선:
```yaml
description: >-
  IT 및 프로그래밍 관련된 글을 작성하는 개발 중심의 블로그입니다. Programming, Development, and Tech blog.
```

## 추가 필요 사항
1. `/assets/img/ogimage.jpg` 경로에 실제 이미지 파일을 업로드해야 합니다.
   - 권장 크기: 1200 x 630 픽셀
   - 파일 크기: 8MB 이하
2. 소셜 미디어 프로필 정보를 실제 본인의 프로필로 업데이트하세요

이러한 변경으로 소셜 미디어 공유와 SEO가 개선될 것입니다.
