### ISSUE TITLE
페이지뷰 추적 설정 오류

### ISSUE THREAD

**Issue by SUNGMYEONGGI** [SUNGMYEONGGI/SUNGMYEONGGI.github.io#4]
## 문제점
현재 `_config.yml`의 페이지뷰 설정에 문제가 있습니다:

```yaml
pageviews:
  provider: goatcounter
```

하지만 GoatCounter ID가 설정되어 있지 않습니다:

```yaml
analytics:
  goatcounter:
    id: # fill in your GoatCounter ID
```

## 해결 완료 ✅
페이지뷰 설정을 다음과 같이 업데이트했습니다:

```yaml
pageviews:
  provider: false  # goatcounter ID가 없으므로 비활성화
```

## 대안
향후 방문자 통계 추적을 원하신다면:

1. Google Analytics를 계속 사용하시거나:
   - 이미 Google Analytics ID (G-XYZ123456)를 설정했으므로 이를 활용할 수 있습니다.

2. GoatCounter를 설정하시려면:
   - https://www.goatcounter.com/ 에서 계정을 생성
   - 발급받은 ID를 config 파일에 추가
   - 페이지뷰 제공자를 goatcounter로 다시 설정

이제 페이지뷰 관련 오류가 더 이상 발생하지 않을 것입니다.
